### ISSUE TITLE
issue with the $_SESSION variable

### ISSUE THREAD

**Issue by frenay** [Philipp15b/php-i18n#19]
In the docs, it is stipulated that the $_SESSION["lang"] variable will be taken into account to choose the language, but I did not find it in the file. I had to add the following lines in "public function getUserLangs()" 

		// 2nd highest priority: GET parameter 'lang'
		if (isset($_GET['lang']) && is_string($_GET['lang'])) {
			$userLangs[] = $_GET['lang'];
		}
		// xxx fix ---
		if (isset($_SESSION['lang']) && is_string($_SESSION['lang'])) {
			$userLangs[] = $_SESSION['lang'];
		}		
		// --- fix xxx
		// Lowest priority: fallback
		$userLangs[] = $this->fallbackLang; 

Did I overlooked something or is it the correct way to do it ?

**Comment by frenay** [comment]
by the way, we should event add these lines at the begining of the fix

	if (session_status() !== PHP_SESSION_ACTIVE) {
		session_start();
	}

**Comment by Philipp15b** [comment]
These lines [already exist](https://github.com/Philipp15b/php-i18n/blob/1d4b49f19ef7b1ee671d0af55af5cdb2fefa0404/i18n.class.php#L243), don't they?

I don't think automatically starting a session is a good idea, because many will use php-i18n without PHP Sessions and this would introduce an unnecessary overhead for them. People who use PHP Sessions (should) already have a call to `session_start()` in their code.
