### ISSUE TITLE
How to disable caching?

### ISSUE THREAD

**Issue by acrolink** [Philipp15b/php-i18n#42]

**Comment by akurucan** [comment]
How to disable caching?

**Comment by emresaracoglu** [comment]
Could you update for the cache disable feature? 
cc @Philipp15b

**Comment by Philipp15b** [comment]
What is your use case for disabled caching? Caching should be cheap - so unless you're modifying your language files __very__ often, you should not notice it. Or are the old cache files are problem? In that case, it would probably better to implement some sort of garbage collection (or simply writing to a single cache file).

**Comment by emresaracoglu** [comment]
This is the reason I want to cancel the cache; #60

**Comment by mcnaveen** [comment]
How I can disable caching?

**Comment by Philipp15b** [comment]
Caching will be based on each user's chosen language as specified in the README. Since this issue seems to confuse more than it helps and there does not seem to be an actual problem so far, I'll close this issue. Feel free to comment if there is a problem.

**Comment by mcnaveen** [comment]
Hi @Philipp15b 

I have a quick question.

As you can see in the Below Snippet. I'm setting the Language filename through the variable `$lang` which is returned from the Database when the user lands on Dashboard after successful login.

```
$i18n = new i18n('lang/lang_' . $lang . '.json', 'langcache/', 'en');
// Parameters: language file path, cache dir, default language (all optional)

// init object: load language files, parse them if not cached, and so on.
$i18n->init();
```

Because you have mentioned `Caching will be based on each user's chosen language` But In my case it's quite different I feel. Is this a right way to do?
