### ISSUE TITLE
Set Default Language to NL instead of EN

### ISSUE THREAD

**Issue by thagxt** [Philipp15b/php-i18n#62]
Let's say I'd like primary language to be Dutch, so when someone visits the site expect the script to load the "lang_nl.json" file but, instead, it loads "lang_en.json".

My code is as follows:
```
$i18n = new i18n('lang/lang_{LANGUAGE}.json, 'cache/', 'nl');
$i18n->setFallbackLang('nl');
$i18n->init();
```
but with this when the person first visits the site and without setting `?lang=nl` it loads the English one...
How can I set nl to be the default?

If I set `$i18n->setForcedLang('nl');` it always uses nl and stops using all other languages.

**Comment by Philipp15b** [comment]
Note: Since the third parameter to the constructor is already the fallback language, you don't need the `setFallbackLang` call.

That said, the library will check the user agent's languages first (unless a forced language is set), so maybe your browser is set to English? Then php-i18n will also try to load the `en` language file. What is the `Accept-Language` HTTP header set to in the request? 

To list all languages the library checks, you could check what's returned by [`getUserLang`](https://github.com/Philipp15b/php-i18n/blob/master/i18n.class.php#L288) using `var_dump` or something.

**Comment by thagxt** [comment]
I've tried and you're right! It depends on the browser language, I also removed the `setFallbackLang` thanks for the heads-up!
